### ISSUE TITLE
【ERROR】 controller could not connect to the switches

### ISSUE THREAD

**Issue by causimmi** [netgroup/rose#6]
Hello, I downloaded your vm and found that the controller could not connect to the switch in the second experiment. Could you please tell me how to deal with it？

```
root@rose-srv6:/home/rose/workspace/rose-srv6-control-plane/control_plane/controll
er# bash starter.sh
WARNING:controller.ti_extraction:pygraphviz library is not installed
Traceback (most recent call last):
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
_**ConnectionRefusedError: [Errno 111] Connection refused**_               <---------------------------------this error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4d39d014f0>: Failed to establish a new connection: [Errno 111] Connection refused             <---------------------------------this error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/urllib3-1.26.5-py3.8.egg/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8529): Max retries exceeded with url: /_db/_system/_api/database (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4d39d014f0>: Failed to establish a new connection: [Errno 111] Connection refused'))          <---------------------------------this error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rose/.envs/controller-venv/bin/controller", line 11, in <module>
    load_entry_point('rose-srv6-control-plane-controller', 'console_scripts', 'controller')()
  File "/home/rose/workspace/rose-srv6-control-plane/control_plane/controller/controller/controller_cli.py", line 190, in __main
    init_db('srv6')
  File "/home/rose/workspace/rose-srv6-control-plane/control_plane/controller/controller/init_db.py", line 52, in init_db
    arangodb_driver.init_db(
  File "/home/rose/workspace/rose-srv6-control-plane/control_plane/controller/controller/arangodb_driver.py", line 121, in init_db
    if sys_db.has_database(db_name):
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/python_arango-5.4.0-py3.8.egg/arango/database.py", line 729, in has_database
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/python_arango-5.4.0-py3.8.egg/arango/database.py", line 719, in databases
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/python_arango-5.4.0-py3.8.egg/arango/api.py", line 66, in _execute
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/python_arango-5.4.0-py3.8.egg/arango/executor.py", line 81, in execute
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/python_arango-5.4.0-py3.8.egg/arango/connection.py", line 154, in send_request
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/python_arango-5.4.0-py3.8.egg/arango/http.py", line 103, in send_request
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8529): Max retries exceeded with url: /_db/_system/_api/database (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4d39d014f0>: Failed to establish a new connection: [Errno 111] Connection refused'))   <---------------------------------this error

```

**Comment by StefanoSalsano** [comment]
the same issue is reported here : https://github.com/netgroup/rose-vm/issues/38

we close this issue here and we will continue to work on https://github.com/netgroup/rose-vm/issues/38
